id: IA1BB940F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T04:19:06+00:00'
last_modified: '2022-06-07T20:32:06.184764+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W28809
  title: གསུང་འབུམ། ངག་དབང་ཉི་མ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    71E9:
      image_group_id: I4808
      title: ''
      total_pages: 726
      order: 1
      base_file: 71E9.txt
    1DFB:
      image_group_id: I4809
      title: ''
      total_pages: 909
      order: 2
      base_file: 1DFB.txt
    '1811':
      image_group_id: I4810
      title: ''
      total_pages: 764
      order: 3
      base_file: 1811.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
