id: IA1BB940F
legacy_id: P004139
ocr_import_info:
  bdrc_scan_id: W28809
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T04:16:56'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T08:43:52.562158+00:00'
last_modified: 2022-09-02 16:53:20.214927
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W28809
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW28809
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ངག་དབང་ཉི་མ།
  author: ངག་དབང་ཉི་མ།
statistics:
  ocr_word_mean_confidence_index: 0.978865406624696
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I4808:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4808
      total_pages: 726
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4808.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9773070237510869
    legacy_id: v001
  I4810:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4810
      total_pages: 764
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I4810.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9786760859654071
    legacy_id: v003
  I4809:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4809
      total_pages: 909
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I4809.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9802825433821447
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
